config/routes.rb
ConnectingLight::Application.routes.draw do
  resources :logs do
    collection do
      get "post" => :create
    end
  end

  get "viz/map"

  resources :admin_settings do
    collection do
      post :send_hello_world_ping
      post :reload_json_settings
      post :send_admin_settings
      post :do_clear_messages
    end
  end

  root to: "application#welcome"
  get "time" => "application#time"
  resources :messages, except: [:edit, :update] do
    collection do
      post :sms
      get :hadrians_mapbox
    end
  end
end

app/models/admin_setting.rb
class AdminSetting < ActiveRecord::Base
  attr_accessible :max, :min, :name, :value

  validate :value_within_range_if_minmax_is_set

  after_save :reset_settings_cache

  def pair
    [name, value]
  end

  def reset_settings_cache
    Rails.cache.write("admin-settings", self.class.get)
  end

  def numeric?
    !!(min || max)
  end

  def value
    if numeric?
      super.to_f
    else
      super
    end
  end

  def step
    (max - min) / 100
  end

  def value_within_range_if_minmax_is_set
    if min && value < min
      errors.add(:value, "can't be smaller than #{min}")
    elsif max && value > max
      errors.add(:value, "can't be larger than #{max}")
    end
  end

  def self.get
    Hash[self.all.map(&:pair)]
  end

  def self.fetch
    Rails.cache.
      fetch("admin-settings") { self.get }.
      merge(time: Time.now.to_i)
  end
end

app/controllers/admin_settings_controller.rb
class AdminSettingsController < ApplicationController
  # GET /admin_settings
  # GET /admin_settings.json
  def index
    @admin_settings = AdminSetting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: AdminSetting.fetch }
    end
  end

  # GET /admin_settings/1
  # GET /admin_settings/1.json
  def show
    @admin_setting = AdminSetting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @admin_setting }
    end
  end

  # GET /admin_settings/new
  # GET /admin_settings/new.json
  def new
    @admin_setting = AdminSetting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @admin_setting }
    end
  end

  # GET /admin_settings/1/edit
  def edit
    @admin_setting = AdminSetting.find(params[:id])
  end

  # POST /admin_settings
  # POST /admin_settings.json
  def create
    @admin_setting = AdminSetting.new(params[:admin_setting])

    respond_to do |format|
      if @admin_setting.save
        format.html { redirect_to @admin_setting, notice: 'Admin setting was successfully created.' }
        format.json { render json: @admin_setting, status: :created, location: @admin_setting }
      else
        format.html { render action: "new" }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin_settings/1
  # PUT /admin_settings/1.json
  def update
    @admin_setting = AdminSetting.find(params[:id])

    respond_to do |format|
      if @admin_setting.update_attributes(params[:admin_setting])
        format.html { redirect_to @admin_setting, notice: 'Admin setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @admin_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_settings/1
  # DELETE /admin_settings/1.json
  def destroy
    @admin_setting = AdminSetting.find(params[:id])
    @admin_setting.destroy

    respond_to do |format|
      format.html { redirect_to admin_settings_url }
      format.json { head :no_content }
    end
  end

  def send_hello_world_ping
    digi_fi_client.send_hello_world_ping
    redirect_to admin_settings_path
  end

  def reload_json_settings
    digi_fi_client.reload_json_settings
    redirect_to admin_settings_path
  end

  def send_admin_settings
    digi_fi_client.send_admin_settings
    redirect_to admin_settings_path
  end

  def do_clear_messages
    digi_fi_client.do_clear_messages
    redirect_to admin_settings_path
  end
end

app/views/admin_settings/_form.html.haml
= form_for @admin_setting do |f|
  -if @admin_setting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@admin_setting.errors.count, "error")} prohibited this admin_setting from being saved:"
      %ul
        - @admin_setting.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :min
    = f.text_field :min
  .field
    = f.label :max
    = f.text_field :max
  .field
    = f.label :value
    = f.text_field :value
  .actions
    = f.submit 'Save'

app/views/admin_settings/edit.html.haml
%h1 Editing admin_setting

= render 'form'

= link_to 'Show', @admin_setting
\|
= link_to 'Back', admin_settings_path

app/views/admin_settings/index.html.haml
%h1 Listing admin_settings

%table.admin_settings
  %tr
    %th Name
    %th{colspan: 2} Value
    %th
    %th
    %th

  - @admin_settings.each do |admin_setting|
    %tr
      %td= admin_setting.name
      - if admin_setting.numeric?
        %td
          = simple_form_for(admin_setting)do |f|
            =f.input :value, label: false
        %td
          .numeric{"data-min" => admin_setting.min,
            "data-max" => admin_setting.max,
            "data-value" => admin_setting.value,
            "data-step" => admin_setting.step,
            "data-post-id" => admin_setting.id}
      - else
        %td{colspan: 2}
          = simple_form_for(admin_setting)do |f|
            =f.input :value, label: false
      %td= link_to 'Show', admin_setting
      %td= link_to 'Edit', edit_admin_setting_path(admin_setting)
      %td= link_to 'Destroy', admin_setting, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Admin setting', new_admin_setting_path

%hr

= button_to 'send_hello_world_ping_admin_settings', send_hello_world_ping_admin_settings_path
= button_to 'reload_json_settings', reload_json_settings_admin_settings_path
= button_to 'send_admin_settings', send_admin_settings_admin_settings_path
= button_to 'do_clear_messages', do_clear_messages_admin_settings_path

:javascript
  $(function(){
    $('form').ajaxForm();
    $('input[type=text]').keydown(function(event){
      $(event.target).closest("form").submit();
    });

    $(".numeric").each(function(){
      var $this = $(this);
      var data = $this.data();
      var options = {
        min: parseFloat(data.min),
        max: parseFloat(data.max),
        value: parseFloat(data.value),
        step: parseFloat(data.step),
        change: function(event, ui) {
          var $form = $("#edit_admin_setting_"+data.postId)
          $form.find("input[type=text]").val(ui.value);
          $form.submit();
        },
        slide: function( event, ui ) {
          var $form = $("#edit_admin_setting_"+data.postId)
          $form.find("input[type=text]").val(ui.value);
        }
      }
      $this.slider(options);
    });
  });

app/views/admin_settings/new.html.haml
%h1 New admin_setting

= render 'form'

= link_to 'Back', admin_settings_path

app/views/admin_settings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @admin_setting.name
%p
  %b Min:
  = @admin_setting.min
%p
  %b Max:
  = @admin_setting.max
%p
  %b Value:
  = @admin_setting.value

= link_to 'Edit', edit_admin_setting_path(@admin_setting)
\|
= link_to 'Back', admin_settings_path