config/routes.rb
ConnectingLight::Application.routes.draw do
  resources :logs do
    collection do
      get "post" => :create
    end
  end

  get "viz/map"

  resources :admin_settings do
    collection do
      post :send_hello_world_ping
      post :reload_json_settings
      post :send_admin_settings
      post :do_clear_messages
    end
  end

  root to: "application#welcome"
  get "time" => "application#time"
  resources :messages, except: [:edit, :update] do
    collection do
      post :sms
      get :hadrians_mapbox
    end
  end
end

app/controllers/admin_messages_controller.rb
class AdminMessagesController < ApplicationController
  respond_to :html, :json

  def index
    @messages = Message.all
    respond_with @messages
  end

  def show
    @message = Message.find(params[:id])

    respond_with @message
  end

  def destroy
    @message = Message.find(params[:id])

    @message.destroy
    respond_with @message
  end
end

app/views/admin_messages/index.html.haml
%h1 Listing messages

=form_for
%table
  %tr
    %th Message
    %th Latitude
    %th Longitude
    %th Ip address
    %th
    %th
    %th
  - @messages.each do |message|
    %tr
      %td= message.message
      %td= message.latitude
      %td= message.longitude
      %td= message.ip_address
      %td= link_to 'Show', message
      %td= link_to 'Edit', edit_message_path(message)
      %td= link_to 'Destroy', message, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Message', new_message_path

app/views/admin_messages/show.html.haml
%p#notice= notice
%p
  %b Message:
  = @message.message
%p
  %b Latitude:
  = @message.latitude
%p
  %b Longitude:
  = @message.longitude
%p
  %b Ip address:
  = @message.ip_address

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path