config/routes.rb
ConnectingLight::Application.routes.draw do
  resources :logs do
    collection do
      get "post" => :create
    end
  end

  get "viz/map"

  resources :admin_settings do
    collection do
      post :send_hello_world_ping
      post :reload_json_settings
      post :send_admin_settings
      post :do_clear_messages
    end
  end

  root to: "application#welcome"
  get "time" => "application#time"
  resources :messages, except: [:edit, :update] do
    collection do
      post :sms
      get :hadrians_mapbox
    end
  end
end

app/models/log.rb
class Log < ActiveRecord::Base
  attr_accessible :message
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logs }
    end
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
    @log = Log.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/new
  # GET /logs/new.json
  def new
    @log = Log.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @log }
    end
  end

  # GET /logs/1/edit
  def edit
    @log = Log.find(params[:id])
  end

  # POST /logs
  # POST /logs.json
  def create
    if params[:log].is_a?(String)
      @log = Log.new(message: params[:log])
    else
      @log = Log.new(params[:log])
    end

    respond_to do |format|
      if @log.save
        format.html { redirect_to @log, notice: 'Log was successfully created.' }
        format.json { render json: @log, status: :created, location: @log }
      else
        format.html { render action: "new" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logs/1
  # PUT /logs/1.json
  def update
    @log = Log.find(params[:id])

    respond_to do |format|
      if @log.update_attributes(params[:log])
        format.html { redirect_to @log, notice: 'Log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log = Log.find(params[:id])
    @log.destroy

    respond_to do |format|
      format.html { redirect_to logs_url }
      format.json { head :no_content }
    end
  end
end

app/views/logs/_form.html.haml
= form_for @log do |f|
  -if @log.errors.any?
    #error_explanation
      %h2= "#{pluralize(@log.errors.count, "error")} prohibited this log from being saved:"
      %ul
        - @log.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :message
    = f.text_area :message
  .actions
    = f.submit 'Save'

app/views/logs/edit.html.haml
%h1 Editing log

= render 'form'

= link_to 'Show', @log
\|
= link_to 'Back', logs_path

app/views/logs/index.html.haml
%h1 Listing logs

%table
  %tr
    %th Message
    %th
    %th
    %th

  - @logs.each do |log|
    %tr
      %td= log.message
      %td= link_to 'Show', log
      %td= link_to 'Edit', edit_log_path(log)
      %td= link_to 'Destroy', log, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Log', new_log_path

app/views/logs/new.html.haml
%h1 New log

= render 'form'

= link_to 'Back', logs_path

app/views/logs/show.html.haml
%p#notice= notice

%p
  %b Message:
  = @log.message

= link_to 'Edit', edit_log_path(@log)
\|
= link_to 'Back', logs_path